export enum OrderStatus {
  PENDING = 'PENDING',
  CANCELED = 'CANCELED',
  PAID = 'PAID',
  CONFIRMED = 'CONFIRMED',
  PROCESSING = 'PROCESSING',
  SHIPPING = 'SHIPPING',
  COMPLETED = 'COMPLETED',
  REFUNDED = 'REFUNDED'
}
