import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import './globals.css'
import { ToastProvider } from '@/providers/toast-provider'
import { ReactQueryClientProvider } from '@/providers/react-query-client-provider'
import { Toaster } from '@/components/ui/sonner'
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import { AppSidebar } from '@/components/app-sidebar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={geistSans.className} suppressHydrationWarning={true}>
        <ReactQueryClientProvider>
          <ToastProvider />
          <Toaster />
          <SidebarProvider>
            <AppSidebar />
            <main className='w-full'>
              <SidebarTrigger />
              {children}
            </main>
          </SidebarProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  )
}
